### ISSUE TITLE
asciiString returning several slashes

### ISSUE THREAD

**Issue by samidalouche** [backchatio/rl#2]
println(Uri("http://wikitravel.org/en/Silicon_Valley").normalize(true).asciiString)

=> returns 
http://wikitravel.org//en/Silicon_Valley/

**Comment by casualjim** [comment]
I'll fix it this weekend.. or send me a pull request :D :D :D .. it should be a really easy fix

**Comment by samidalouche** [comment]
What about 

```
val schemeAndAuthority = scheme.uriPart + authority.map(_.uriPart.dropRight(1)).getOrElse("")
val afterAuthority = segments.uriPart + query.uriPart + fragment.uriPart

if (afterAuthority.isEmpty)
  schemeAndAuthority + "/"
else
  schemeAndAuthority + afterAuthority
```

**Comment by casualjim** [comment]
thanks a lot :)  will add this code tonight after work
